clip_model = "ViT-L/14"
source = "openai"
[scores]
sexual = 0.2
nude = 0.2
sex = 0.206
"18+" = 0.21
naked = 0.195
nsfw = 0.2
porn = 0.2
dick = 0.19
vagina = 0.19
"naked child" = 0.22
"explicit content" = 0.19
"uncensored" = 0.2
"fuck" = 0.2
"nipples" = 0.2
"visible nipples" = 0.21
"naked breasts" = 0.214
"areola" = 0.2



